title: OdnetninI
email: odnetnininds@gmail.com
description: "Algunas cosas locas que pueden ser de programación, de youtube, de videojuegos (como el WoW), o cualquier cosa que me apetezca decir."
biography: "Soy OdnetninI estudiante de Ingeniería Informática."
colophon: "© OdnetninI (odnetnininds@gmail.com).<br>Content under <a href=\"https://www.gnu.org/licenses/gpl-3.0.en.html\">GPL 3.0</a>."
baseurl: ""
url: "https://odnetnini.ml" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: odnetnini
github_username:  odnetnini
youtube_username: odnetnini
twitch_username: odnetnini

markdown: kramdown
simple_search: http://google.com/search
permalink: /blog/:year/:month/:day/:title/

highlighter: rouge
plugins:
  - jekyll-feed
